# Generated by Django 4.2.7 on 2023-11-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('birth', models.DateField(max_length=20)),
                ('enter', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('handtype', models.CharField(max_length=20)),
                ('ispitcher', models.BooleanField()),
                ('games', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PitcherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.FloatField()),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('save', models.IntegerField()),
                ('hold', models.IntegerField()),
                ('K', models.IntegerField()),
                ('WHIP', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dooboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='BatterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AVG', models.FloatField()),
                ('OBP', models.IntegerField()),
                ('SLG', models.IntegerField()),
                ('PA', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('homerun', models.IntegerField()),
                ('BOB', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dooboard.player')),
            ],
        ),
    ]
