# Generated by Django 4.2.7 on 2023-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherdata',
            old_name='WHIP',
            new_name='ERA',
        ),
        migrations.AlterField(
            model_name='batterdata',
            name='OBP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterdata',
            name='SLG',
            field=models.FloatField(),
        ),
    ]
