# Generated by Django 4.2.7 on 2023-11-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dooboard', '0003_player_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherdata',
            old_name='save',
            new_name='saves',
        ),
    ]
