# Generated by Django 4.2.7 on 2023-11-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooboard', '0005_pitcherdatals_batterdatals'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curgames',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
