# Generated by Django 4.2.7 on 2023-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooboard', '0009_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
