# Generated by Django 4.2.7 on 2023-11-09 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dooboard', '0010_reply_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='voterd',
            field=models.ManyToManyField(related_name='voterd_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='voteru',
            field=models.ManyToManyField(related_name='voteru_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='voterd',
            field=models.ManyToManyField(related_name='voterd_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='voteru',
            field=models.ManyToManyField(related_name='voteru_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
