# Generated by Django 4.2.7 on 2023-11-09 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dooboard', '0011_player_voterd_player_voteru_reply_voterd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='voterd',
            field=models.ManyToManyField(null=True, related_name='voterd_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='voteru',
            field=models.ManyToManyField(null=True, related_name='voteru_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voterd',
            field=models.ManyToManyField(null=True, related_name='voterd_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voteru',
            field=models.ManyToManyField(null=True, related_name='voteru_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
