# Generated by Django 4.2.7 on 2023-11-10 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dooboard', '0012_alter_player_voterd_alter_player_voteru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='voterd',
            field=models.ManyToManyField(related_name='voterd_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='voteru',
            field=models.ManyToManyField(related_name='voteru_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voterd',
            field=models.ManyToManyField(related_name='voterd_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='voteru',
            field=models.ManyToManyField(related_name='voteru_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
