# Generated by Django 4.2.7 on 2023-11-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dooboard', '0015_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterdatals',
            old_name='AVG',
            new_name='AVGl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='BOB',
            new_name='BOBl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='OBP',
            new_name='OBPl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='PA',
            new_name='PAl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='SLG',
            new_name='SLGl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='hit',
            new_name='hitl',
        ),
        migrations.RenameField(
            model_name='batterdatals',
            old_name='homerun',
            new_name='homerunl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='ERA',
            new_name='ERAl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='K',
            new_name='Kl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='hold',
            new_name='holdl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='inning',
            new_name='inningl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='loss',
            new_name='lossl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='saves',
            new_name='savesl',
        ),
        migrations.RenameField(
            model_name='pitcherdatals',
            old_name='win',
            new_name='winl',
        ),
    ]
